version: 2

models:
  - name: pageviews
    description: >
      Individual page view events with web analytics metrics including time on page,
      navigation flow, and engagement metrics.
    columns:
      - name: event_timestamp
        description: Timestamp of the page view event (microseconds since epoch)
        tests:
          - not_null

      - name: user_pseudo_id
        description: Unique identifier for the user
        tests:
          - not_null

      - name: ga_session_id
        description: GA4 session identifier
        tests:
          - not_null

      - name: page_location
        description: Full URL of the page viewed

      - name: page_path
        description: Path portion of the URL

      - name: page_hostname
        description: Hostname portion of the URL

      - name: time_on_page_seconds
        description: Time spent on page before next page view

      - name: is_entrance
        description: Flag indicating if this is the first page of the session (1=yes, 0=no)

      - name: is_exit
        description: Flag indicating if this is the last page of the session (1=yes, 0=no)

      - name: page_number_in_session
        description: Sequential order of this page view within the session

  - name: users
    description: >
      User-level aggregations with RFM segmentation, lifetime value metrics,
      and attribution data.
    columns:
      - name: user_pseudo_id
        description: Unique identifier for the user
        tests:
          - not_null
          - unique

      - name: total_sessions
        description: Total number of sessions for this user
        tests:
          - not_null

      - name: total_revenue
        description: Lifetime revenue generated by this user

      - name: user_conversion_rate
        description: Percentage of sessions that resulted in a purchase

      - name: user_type
        description: Classification of user (Repeat Buyer, One-Time Buyer, etc.)

      - name: recency_segment
        description: RFM recency segment based on days since last visit

      - name: frequency_segment
        description: RFM frequency segment based on total sessions

      - name: monetary_segment
        description: RFM monetary segment based on total revenue

  - name: add_to_cart_events
    description: >
      Product add-to-cart events with item details, pricing, and context.
    columns:
      - name: event_timestamp
        description: Timestamp of the add-to-cart event
        tests:
          - not_null

      - name: user_pseudo_id
        description: Unique identifier for the user
        tests:
          - not_null

      - name: item_id
        description: Product ID that was added to cart
        tests:
          - not_null

      - name: item_value
        description: Total value of the item(s) added (price * quantity)

  - name: purchase_events
    description: >
      Purchase transactions with product details, revenue metrics, and time-to-purchase analytics.
    columns:
      - name: event_timestamp
        description: Timestamp of the purchase event
        tests:
          - not_null

      - name: user_pseudo_id
        description: Unique identifier for the user
        tests:
          - not_null

      - name: transaction_id
        description: Unique transaction identifier (may be null in some cases)

      - name: item_revenue_usd
        description: Revenue from this line item in USD

      - name: days_to_purchase_from_first_visit
        description: Number of days from user's first visit to this purchase

  - name: product_views
    description: >
      Product detail page view events with product information and context.
    columns:
      - name: event_timestamp
        description: Timestamp of the product view event
        tests:
          - not_null

      - name: user_pseudo_id
        description: Unique identifier for the user
        tests:
          - not_null

      - name: item_id
        description: Product ID that was viewed
        tests:
          - not_null

  - name: conversion_funnel
    description: >
      Daily conversion funnel metrics showing progression through the customer journey
      with conversion rates and drop-off analysis by traffic source, device, and geography.
    columns:
      - name: event_date
        description: Date of the funnel data
        tests:
          - not_null

      - name: total_sessions
        description: Total sessions for this segment
        tests:
          - not_null

      - name: session_overall_conversion_rate
        description: Percentage of sessions that resulted in a purchase

      - name: sessions_with_purchase
        description: Number of sessions with at least one purchase

  - name: sessions
    description: >
      GA4 session-level data aggregated from raw events. Each row represents a unique session
      with metrics like page views, events, engagement time, and revenue.
    columns:
      - name: event_date
        description: Date of the session (parsed from YYYYMMDD format)
        tests:
          - not_null

      - name: user_pseudo_id
        description: Unique identifier for the user
        tests:
          - not_null

      - name: ga_session_id
        description: GA4 session identifier
        tests:
          - not_null

      - name: session_start_timestamp
        description: Timestamp when the session started (microseconds since epoch)

      - name: session_end_timestamp
        description: Timestamp when the session ended (microseconds since epoch)

      - name: session_duration_seconds
        description: Duration of the session in seconds

      - name: page_views_per_session
        description: Number of page_view events in the session

      - name: events_per_session
        description: Total number of events in the session

      - name: session_engagement_time_msec
        description: Total engagement time during the session in milliseconds

      - name: traffic_source_name
        description: Name of the traffic source campaign

      - name: traffic_source_medium
        description: Medium of the traffic source (e.g., organic, cpc, referral)

      - name: traffic_source_source
        description: Source of the traffic (e.g., google, facebook)

      - name: purchase_events_per_session
        description: Number of purchase events in the session

      - name: purchase_revenue_per_session
        description: Total purchase revenue in USD for the session

      - name: is_conversion_session
        description: Binary flag indicating if the session had at least one purchase (1=yes, 0=no)

      - name: device_category
        description: Category of the device (mobile, desktop, tablet)

      - name: device_operating_system
        description: Operating system of the device

      - name: device_browser
        description: Browser language setting

      - name: geo_continent
        description: Continent of the user

      - name: geo_sub_continent
        description: Sub-continent of the user

      - name: geo_country
        description: Country of the user

      - name: geo_region
        description: Region/state of the user

      - name: geo_city
        description: City of the user
