version: 2

sources:
  - name: ga4_obfuscated_sample_ecommerce
    database: bigquery-public-data
    schema: ga4_obfuscated_sample_ecommerce
    description: >
      Google Analytics 4 obfuscated sample ecommerce dataset from BigQuery Public Data.
      Contains event-level data from a sample ecommerce site.

    tables:
      - name: events_
        description: >
          Wildcard table containing all GA4 events. Use with _TABLE_SUFFIX filter
          to query specific date ranges. Each row is an individual event.
        identifier: "events_*"

        columns:
          - name: event_date
            description: The date when the event was logged (YYYYMMDD format)

          - name: event_timestamp
            description: The time (in microseconds, UTC) when the event was logged

          - name: event_name
            description: The name of the event

          - name: user_pseudo_id
            description: The pseudonymous ID for the user

          - name: event_params
            description: Array of event parameters (key-value pairs)

          - name: ecommerce
            description: Ecommerce-related event parameters

          - name: items
            description: Array of items associated with the event

          - name: traffic_source
            description: Traffic source information

          - name: device
            description: Device information

          - name: geo
            description: Geographic information

  - name: snowplow_ecommerce_sample
    database: ra-warehouse-dev
    schema: snowplow_ecommerce_sample
    description: >
      Snowplow event tracking data with GA4 ecommerce events captured via
      GTM and sent to both GA4 and Snowplow. Contains 100 sample events.

    tables:
      - name: events
        description: >
          Snowplow events table with GA4 ecommerce plugin enabled. Each row
          is an individual event with Snowplow-specific enrichments.

        columns:
          - name: event_id
            description: Unique identifier for the event (UUID)

          - name: event_name
            description: The name of the event (e.g., add_to_cart, purchase)

          - name: collector_tstamp
            description: The timestamp when the event was collected

          - name: user_pseudo_id
            description: The pseudonymous ID for the user

          - name: session_id
            description: The session identifier

          - name: ecommerce
            description: Ecommerce-related event parameters

          - name: device
            description: Device information struct

          - name: geo
            description: Geographic information struct

          - name: traffic_source
            description: Traffic source information struct

          - name: page_location
            description: The URL of the page

          - name: page_title
            description: The title of the page

          - name: user_properties
            description: Custom user properties (loyalty tier, segment, etc.)

          - name: ga4_adapter
            description: Metadata about the GA4 adapter
